# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    deps: [check]

  check:
    - task: tests
    - task: doc
    - task: lints
    - task: fmtchk
    - git diff --exit-code

  doc:
    cmds:
      - cargo doc {{.FEATURE}} {{.DOC}} {{.CLI_ARGS}}
    env:
      RUSTDOCFLAGS: "{{.RUSTDOC}}"
  fix: cargo clippy --fix {{.TARGET}} {{.FEATURE}} {{.CLIPPY}} {{.CLI_ARGS}}
  fmt: cargo fmt {{.FMT}} {{.CLI_ARGS}}
  fmtchk: cargo fmt --check {{.FMT}} {{.CLI_ARGS}}
  lint: cargo clippy {{.TARGET}} {{.FEATURE}} {{.CLIPPY}} {{.CLI_ARGS}}
  test:
    cmds:
      - cargo test {{.TARGET}} {{.FEATURE}} {{.TEST}} {{.CLI_ARGS}}
      - cargo test --doc {{.TEST}} {{.CLI_ARGS}}
    env:
      RUST_BACKTRACE: 1

  lints:
    cmds:
      - task: run
        vars: { TASK: lint }
  tests:
    cmds:
      - task: run
        vars: { TASK: test }
  run:
    desc: Run the `TASK` variable for all features
    cmds:
      - for: { var: FEATURES }
        task: '{{.TASK}}'
        vars:
          FEATURE: '{{.ITEM}}'

  install-git-hooks:
    desc: Create git hooks
    cmds:
      - echo '#!/bin/sh' > .git/hooks/pre-push
      - echo 'task check' >> .git/hooks/pre-push
      - cmd: chmod +x .git/hooks/pre-push
        platforms: [linux, darwin]

vars:
  CLIPPY: '-- -Dwarnings'
  DOC: --no-deps --workspace --document-private-items
  FEATURE: ''
  FEATURES: ['']
  FMT: '--all'
  RUSTDOC: -Dwarnings
  TARGET: '--all-targets'
  TEST: ''
